FROM apache/superset
RUN pip install clickhouse-sqlalchemy==0.2.3
RUN superset fab create-admin \
	--username admin \
    --firstname Superset \
    --lastname Admin \
    --email admin@superset.com \
    --password admin
RUN superset db upgrade
RUN superset init
